### ISSUE TITLE
Créer une archive ready-to-use

### ISSUE THREAD

**Issue by SolidOrphan** [maelsoucaze/flarum#11]
Dans l'archive ZIP disponible au téléchargement, j'ai pensé pour plus de facilité, de créer directement le squelette pour pouvoir dézipper sans créer de dossier.
Actuellement : /flarum-master/
Souhait : /extensions/french/

Cordialement,

**Comment by maelsoucaze** [comment]
C'est ce que j'avais prévu à la base, mais j'ai modifié ça (9bce70232c9f12a87119cc59c9a56b0659142f40) car le créateur de Flarum me l'a conseillé.

Il faut savoir que l'installation "manuelle" des extensions n'est que temporaire. Si cette méthode est la seule à l'heure actuelle, elle ne sera pas conseillée à l'avenir. Il est prévu qu'il y ai un magasin d'extensions où il sera possible d'installer et de désinstaller les extensions d'un seul clic depuis l'administration, un peu comme les magasins d'applications de type Marketplace / Google Play Store.
