### ISSUE TITLE
Flarum beta2

### ISSUE THREAD

**Issue by Petrouchka** [maelsoucaze/flarum#15]
After installing beta 2, there's a new line in english at the first page :

"Looks like there are no discussions here. Why don't you create a new one?"

![capture-discussions gnu-linux et logiciels libres - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9871064/4288a7be-5b91-11e5-96c6-2be92042315a.png)

**Comment by maelsoucaze** [comment]
Yeah, it's hard coded into the Flarum's core and should be moved as locale in the future.
