### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by modInfo** [maelsoucaze/flarum#6]
[Sat Aug 29 12:01:24.909933 2015] [:error] [pid 19226] [client 198.41.241.25:63624] PHP Notice:  Undefined variable: class in /var/www/flarum/flarum/vendor/flarum/core/src/Support/ExtensionManager.php on line 130, referer: http://example.com/admin
[Sat Aug 29 12:01:24.909975 2015] [:error] [pid 19226] [client 198.41.241.25:63624] PHP Fatal error:  Call to a member function install() on null in /var/www/flarum/flarum/vendor/flarum/core/src/Support/ExtensionManager.php on line 58, referer: http://example.com/admin

**Comment by maelsoucaze** [comment]
Can I have some more informations please? Flarum worked properly before using the extension? Do you followed [the documentation] (https://github.com/maelsoucaze/flarum#documentation) properly?

**Comment by tobscure** [comment]
@modInfo Make sure you've got the latest version of the extension; there should be a `vendor` directory present.

**Comment by maelsoucaze** [comment]
Especially this fix: 1608c2119b797524e78005db12ea8816fb87e4a9

**Comment by modInfo** [comment]
it works now, thanks
